version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: situational-llm:v1.0.0
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - data_volume:/workspace/data
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  data_volume:
    driver: local
